#/*
# * StaffChat, Een simple staffchat plugin!
# * Copyright (C) 2022 Justin. K <Crqptx@gmail.com>
# *
# * This program is free software: you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation, either version 3 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program.  If not, see <https://www.gnu.org/licenses/>.
# */

# Plugin gemaakt door: Crqptx

# Github: Falterrie
# Copyright: Zie bovenstaande (MIT)


# ----------------------
Version: "1.0"
# ----------------------

# ----------------------
# STAFFCHAT
# ----------------------

Prefix: "&8&lDark&7&lKingdom &0&l> "
ColorBeforeName: "&4"
ColorAfterName: "&4"

# ----------------------

No Permission: "&4ERROR: Je hebt hier geen permissie voor!"