name: StaffChat
version: '1.0-SNAPSHOT'
main: me.crqptx.main.StaffChat
authors: [ Crqptx ]
description: Staffchat plugin
commands:
  sc:
    description: Staffchat command
    usage: /<command> <text>
    aliases: [ staffchat ]
  screload:
    description: Reloads the plugin
    usage: /<command>